# Generated by Django 5.1 on 2024-08-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_homesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
    ]
